version: '3.8'
services:
 frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network
 backend:
   build:
    context: ./server
    dockerfile: Dockerfile
   container_name: backend
   ports:
      - "5000:5000"
    # Remove or comment out the 'depends_on' block for MongoDB
    # depends_on:
    #   - mongodb
   networks:
      - my_network 
 mongodb:
        image: mongo:latest
        ports:
              - "27017:27017"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
          - mongo-data:/data/db
 mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
          - "8081:8081"
        environment:
          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
          - ME_CONFIG_MONGODB_ADMINPASSWORD=password
          - ME_CONFIG_MONGODB_SERVER=mongodb
          - ME_CONFIG_MONGODB_PORT=27017
# Define named volumes
volumes:
  mongo-data:
    driver: local
networks:
  my_network:
    driver: bridge

