version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
volumes:
  data:
  logs:
